# Binomial Distributions
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

In [48]:
# import numpy
import numpy as np
import math

### 1. A fair coin flip produces heads

In [49]:
# simulate 1 million tests of one fair coin flip
# remember, the output of these tests are the # successes, or # heads
tests = np.random.binomial(1, 0.5, int(1e6))

tests

array([1, 1, 0, ..., 0, 0, 0])

In [50]:
# proportion of tests that produced heads
(tests == 1).mean()

0.500529

### 2. Five fair coin flips produce exactly one head

In [51]:
tests = np.random.binomial(5, 0.5, size=(int(1e6)))
tests

array([3, 2, 4, ..., 1, 3, 2])

In [52]:
# proportion of tests that produced 1 head
(tests == 1).mean()

0.156277

#### Theory

In [75]:
# number of different types of outcome in total
binomial = 2
n = 5
k = 1
nr_out_total = binomial**n

# number of possible ourcomes with 1 head?
nr_out_k = math.factorial(n) / (math.factorial(n - k) * math.factorial(k))
nr_out_k

# p(1 head from 5 flips)
p = nr_out_k / nr_out_total

print(nr_out_k, '/', nr_out_total, '=', p)

5.0 / 32 = 0.15625


### 3. Ten fair coin flips produce exactly four heads

In [39]:
# simulate 1 million tests of ten fair coin flips
tests = np.random.binomial(10, 0.5, size=(int(1e6)))

tests

array([3, 4, 4, ..., 5, 5, 7])

In [44]:
# proportion of tests that produced 4 heads
(tests == 4).mean()

0.204991

In [79]:
# number of different types of outcome in total
binomial = 2  # for binomial this ia always 2
n = 10        # number of tosses 
k = 4         # number of exactly this value true
nr_out_total = binomial**n

# number of possible ourcomes with 1 head?
nr_out_k = math.factorial(n) / (math.factorial(n - k) * math.factorial(k))
nr_out_k

# p(1 head from 5 flips)
p = nr_out_k / nr_out_total

print(nr_out_k, '/', nr_out_total, '=', p)

210.0 / 1024 = 0.205078125


### 4. Five biased coin flips with P(H) = 0.8 produce exactly five heads

#### Simulation

In [86]:
# simulate 1 million tests of five biased coin flips
tests = np.random.binomial(5, 0.8, size=(int(1e6)))

tests

array([4, 4, 5, ..., 5, 4, 3])

In [88]:
# proportion of tests that produced 5 heads
(tests == 5).mean()

0.327466

#### Theory

In [107]:
# number of different types of outcome in total
binomial = 2  # for binomial this ia always 2
n = 5        # number of tosses 
k = 5        # number of exactly this value true
nr_out_total = binomial**n

# number of possible ourcomes with 1 head?
nr_out_k = math.factorial(n) / (math.factorial(n - k) * math.factorial(k))
nr_out_k

# # p(1 head from 5 flips)

# p = nr_out_k / nr_out_total

# print(nr_out_k, '/', nr_out_total, '=', p)



1.0

In [109]:
(0.8 * 0.8 * 0.8 * 0.8 * 0.8) * nr_out_k

0.32768000000000014

### 5. Ten biased coin flips with P(H) = 0.15 produce at least 3 heads

#### Simulation

In [110]:
# simulate 1 million tests of ten biased coin flips
tests = np.random.binomial(10, 0.15, size=1000000)

tests

array([0, 1, 2, ..., 4, 0, 4])

In [111]:
# proportion of tests that produced at least 3 heads
(tests == 3).mean()

0.130157

#### Theory

In [112]:
n = 10 
k = 3
num = math.factorial(n) / ( math.factorial(n - k) * math.factorial(k) )
num

120.0

In [113]:
num * (0.15 * 0.15 * 0.15 * 0.85 * 0.85 * 0.85 * 0.85 * 0.85 * 0.85 * 0.85)

0.1298337207539062